name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact_name:
        description: 'Name of the artifact files'
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
      - name: List files
        run: ls    
      - name: Output info
        run: echo "Deploying... and uploading..."