name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact_name:
        description: 'Name of the artifact files'
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: 'The result of the deployment'
        value: ${{ jobs.deploy.outputs.outcome }}    
    #secrets:
      #some_secret:
        #required: false
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
      - name: List files
        run: ls    
      - name: Output info
        run: echo "Deploying... and uploading..."
      - name: Set result output
        id: set-result
        run: echo "::set-output=success" >> $GITHUB_OUTPUT 